server:
  post: 9100
spring:

  #   Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/jb_user_atom
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  #   Hibernate Config
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true